### ISSUE TITLE
quad.jl + qnwbeta

### ISSUE THREAD

**Issue by Jovansam** [QuantEcon/QuantEcon.jl#263] opened 2020-07-02 13:29 UTC
Warning: `lgamma(x::Real)` is deprecated, use `(logabsgamma(x))[1]` instead.
│   caller = qnwbeta(::Int64, ::Float64, ::Float64) at quad.jl:382
└ @ QuantEcon ...\.julia\packages\QuantEcon\vVeHL\src\quad.jl:382

**Comment by sglyon** [comment] 2020-07-02 13:31
Thanks @Jovansam would you be willing to make this change in a pull request?

**Comment by Jovansam** [comment] 2020-07-02 13:32
Unfortunately, I am new to github and julia. Might break more things than I can fix. But will learn slowly, and in future I will.

**Comment by sglyon** [comment] 2020-07-02 15:44
No problem, reporting the issue is quite helpful!

**Comment by oyamad** [comment] 2022-07-05 17:00
Has already been fixed by #264.

**Closed by oyamad** 2022-07-05 17:00 UTC
