### ISSUE TITLE
MarkovChain: state_values related

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.jl#119] opened 2016-07-10 12:17 UTC
1. Change
   - (`simulate`, `simulate_values`) to (`simulate_indices`, `simulate`)
   - (`simulation`, `value_simulation`) to (`simulation_indices`, `simulation`)?
2. For the new `simulate` (current `simulate_values`), `init` should be specified as a state value, not index. Need a method to return the index in `state_values` given a state value (for the Python version, see https://github.com/QuantEcon/QuantEcon.py/pull/237/commits/5bc78d5706462cde82dcba09dfec114c2a3e4680).
3. Let `recurrent_classes` and `communication_classes` return state values, and add `*_indices`.

**Comment by oyamad** [comment] 2016-07-16 13:42
`simulate_values!(mc::MarkovChain, init_state::Vector{Int}, X::Matrix)` currently works as follows:

```jl
julia> mc = MarkovChain([0 1; 1 0]);

julia> X = Array(Int, 5, 2);

julia> init_state = [1, 2];

julia> simulate_values!(mc, init_state, X)
5x2 Array{Int64,2}:
 4448600528  4448600944
          2           1
          1           2
          2           1
          1           2
```

It should be better to fill `X[1, :]` with the initial state values.

**Comment by jstac** [comment] 2016-07-20 03:26
@oyamad I'm confused.  What's the difference between `simulation` and `simulate`?   It seems confusing to have both for instances of `MarkovChain`.

**Comment by oyamad** [comment] 2016-07-20 03:42
`simulation` returns a `Vector`, while `simulate` returns a `Matrix` (even when num_reps=1) (https://github.com/QuantEcon/QuantEcon.jl/pull/99#issuecomment-197412344). I agree it can be confusing, but I have no good idea for alternatives.

**Comment by jstac** [comment] 2016-07-20 04:05
Thanks.  I guess I knew that and forgot.  Let's open this up to discussion.

First, I like @oyamad 's plan to unify names with what we have in Python.  The Python conventions are simple and clear.  In Python we only have `simulate` and `simulate_indices`, each of which generate a single time series.  So my preference is:

1. Change (`simulate`, `simulate_values`) to (`simulate_indices`, `simulate`) and have them return flat arrays.

2. Drop `simulation` and `value_simulation`.

**Comment by oyamad** [comment] 2016-07-20 04:15
To clarify, in the Python version, `simulate` (and `simulate_indices`) returns a 1d array if `num_reps` is not supplied, and a 2d array otherwise (http://quanteconpy.readthedocs.io/en/latest/markov/core.html#quantecon.markov.core.MarkovChain.simulate). We need a clever idea if we want to follow this in the Julia side with one function name while keeping type stability.

**Comment by jstac** [comment] 2016-07-20 05:08
I see.

How about `simulate` gives a single chain and returns a 1d array, while `simulate_panel` generates a 2d "panel"?

(This corresponds to the meaning of panel data)

Similarly, `simulate_indices` gives indices in 1d, while `simulate_panel_indicies` gives the 2d version?

**Comment by jstac** [comment] 2016-08-02 02:34
Partly related question:  Is this line

https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/markov/mc_tools.jl#L426

with `init_state::Int` we are passing an index.  In the Python version we pass a value.  

I guess both are OK as long as the documentation is clear.

**Comment by jstac** [comment] 2016-08-03 21:33
@albep @vgregory757 If either or both of you are able to contribute to finishing the debate and closing out this issue I would be grateful.

Apart from `simulate_panel`, `simulate_cross_section` could also be a good option.  It's a bit verbose but I think the meaning is clear from the name.

Whatever decisions are made this will affect the lecture site and applications repo, so please coordinate with me.

Thanks, J.

**Comment by albep** [comment] 2016-08-04 16:14
Am I correct in saying that in the Julia `simulate` function we need an actual `Matrix` to be returned if either of 3 things happens: i) a vector of initial conditions is supplied (but `num_reps` = 1); ii) only 1 initial condition is supplied but `num_reps` > 1; iii) a vector of initial conditions is supplied and `num_reps` > 1. I'm looking at this line https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/markov/mc_tools.jl#L315. My question then is: when are cases i) and iii) relevant? Otherwise we could use only 2 functions (`simulate` and `simulate_indices`) that return a flat array or a 2d array based on 2 methods, depending on whether `init` is a number or an array - where the array corresponds to cases when we want more than 1 repetition. This cannot handle on its own situations where we want some assigned initial conditions to be repeated multiple times, but we can just generate the appropriate initial conditions outside of the function, and then apply the method on that vector of initial conditions

**Comment by vgregory757** [comment] 2016-08-04 17:31
I agree that the current setup of the functions is confusing and that the names `simulation` and `value_simulation` are unclear. I like @albep's suggestion -- would it mean that there would be no `num_reps` argument? If so, one downside to that might be that it's departing from the way the Python code is set up. 

Whatever we decide, I'd be happy to help make any changes to the functions/existing code that calls them.

**Comment by cc7768** [comment] 2016-08-04 17:46
@spencerlyon2 probably knows a bit more about what is happening behind the scenes, so he can comment on this thought (and probably improve it).

I agree with John with respect to having the exposed function names match up to the Python code. It might not be that big of a deal to make the `simulate` function consistent in its return type if the returned value is generated within a different function (which does consistently deal with the same types so will compile nicely). In my mind I have something like the following:

```
function simulate(mc::MarkovChain; npers::Int, nreps::Int=1)
    # Farm out to the right method
    if nreps == 1
        out = simulate_single_chain(mc, npers)
    else
        out = simulate_panel(mc, npers, nreps)
    end

    return out
end

function simulate_single_chain(mc::MarkovChain, npers::Int)
   # Do stuff......
   # Return a 1d array of the simulation
end

function simulate_panel(mc::MarkovChain, npers::Int, nreps::Int)
  # Do stuff
  # Return a 2d array with each simulation down column
end
```

All the work is happening within functions that return the same type of thing each time, so I don't think we would suffer much slow down. Additionally, we would only export the single `simulate` function so users don't even have to know about these other pieces.

**Comment by jstac** [comment] 2016-08-05 04:34
@cc7768 That sounds like a smart way to go.  As you say, each function handles a different case, so there should be no performance issues.  

I should say I also like @albep 's suggestion that the function the user calls figures out whether it's a single chain or a cross-section of multiple changes from the `init` argument.  If it's a single element then you get back a single chain.  If it's an array, then you get back a matrix with one chain per element of the array.

**Comment by spencerlyon2** [comment] 2016-08-05 07:48
Thanks @cc7768. Your analysis of the type inference implications _within_ the `simulate` function is exactly right.

However, the issue is that the `simulate` function itself will not be type stable. This means anyone that calls that function will have to deal with the type instability. My rule of thumb is that I try to figure out how to make _library_ functions type stable so that users of the library can trust that calling our routines will still allow their code to be compiled efficiently.

I haven't thought of a clever way to do this, but when I do I'll post here.

A non-clever way to do it would be to always return a 2 dimensional array, where the `size` would be `(N, 1)` in cases where we previously returned a 1d array. I don't love that solution though, so let's keep thinking

**Comment by albep** [comment] 2016-08-05 08:33
This would be a way to implement what I had in mind, using only method inference:

`function _simulate(mc::MarkovChain, ts_length::Int, init::Int)
  # return 1d simulation of mc with init as initial index
end

function _simulate(mc::MarkovChain, ts_length::Int, init::Vector{Int})
  # return 2d simulation of mc with init as vector of initial indeces
end

function _simulate(mc::MarkovChain, ts_length::Int; num_reps::Int = 1)
  init = rand(1:size(mc.p, 1), num_reps)
  _simulate(mc, ts_length, init)
  # return 1d(2d) simulation of mc with random initial index(ces)
end

function _simulate(mc::MarkovChain, ts_length::Int, num_reps::Int, init::Vector{Int})
  _simulate(mc, ts_length, repmat(init, num_reps))
  # return 2d simulation of mc with init as vector of initial indeces, repeated num_reps times
end`

It covers all cases as the current code. However it doesn't address @spencerlyon2 point, which I think is important: so far we discussed returning flat or 2d arrays, but the user would then have to face the type instability induced by the library function `simulate`. So the goal is really to always return the same type. Unless we create a new type to achieve that type stability (a type which is always the same, regardless of whether we have 1 or multiple series simulated),  the only alternative I see is a 2d array as @spencerlyon2 said

**Comment by oyamad** [comment] 2016-08-05 12:01
Always returning a 2d array doesn't sound a bad idea.

**Comment by jstac** [comment] 2016-08-05 19:12
Personally I would say that the case of wanting to generate a cross section is significantly less common than wanting to generate a single chain.  So, rather than always returning a 2D array, my vote would be to just drop the methods that generate multiple chains in cross section.  Instead we should only have routines that generate a single chain returned as a flat array, and any user who wants a cross section just sets up a loop.  Julia being Julia, there will be no issue with performance.

Generating a cross section is probably more important in a language where vectorization is necessary.  That's not the case here.

**Comment by spencerlyon2** [comment] 2016-08-08 07:43
Here's an idea.

What if we have `simulate` and `simulate_indices` always return a flat array (Vector), but also expose methods `simulate!` and `simulate_indices!` that will fill a pre-allocated array with as many chains as there are columns in the pre-allocated array.

I think that the `init` argument for these methods should do the following:

- if not given, create a new random initial condition for each chain
- If a scalar is given, apply the same initial condition to each chain
- If a vector is given, then apply each element of the vector as an initial condition for one chain, repeating the conditions as necessary. Specifically I have the following in mind:

```julia
real_init = collect(take(cycle(init), size(out, 2)))
```

An example of this behavior is here:

```
julia> out = zeros(10, 5);

julia> init = [1, 2, 3];

julia> real_init = collect(take(cycle(init), size(out, 2)))
5-element Array{Int64,1}:
 1
 2
 3
 1
 2
```

The alternative to this more robust, more magical proposal would be to throw an error whenever `1 < length(init) < size(out, 2)`

Any comments/suggestions on this proposal?

**Comment by jstac** [comment] 2016-08-08 11:10
I like this idea.  

Either of the alternative approaches to treating `init` is fine, as long as it's clearly documented.

**Comment by spencerlyon2** [comment] 2016-08-09 21:29
Sounds good to me. @vgregory757 or @albep are either of you willing to take this on?

**Comment by vgregory757** [comment] 2016-08-10 14:26
Sure. I'll start by implementing @spencerlyon2's idea(s) and submit a PR asap.

**Closed** 2016-11-15 12:27 UTC
