### ISSUE TITLE
Error message in mc_sample_path

### ISSUE THREAD

**Issue by ranjanan** [QuantEcon/QuantEcon.jl#52] opened 2015-06-28 17:29 UTC
I receive an error message on using mc_sample_path()

julia> using QuantEcon

julia> P = [0.4 0.6; 0.8 0.2]
2x2 Array{Float64,2}:
 0.4  0.6
 0.8  0.2

julia> P = MarkovChain(P)
Discrete Markov Chain
stochastic matrix:
2x2 Array{Float64,2}:
 0.4  0.6
 0.8  0.2

julia> mc_sample_path(P, [0.5, 0.5], 100000)
ERROR: type cannot be constructed
 in map at abstractarray.jl:1328

I'm using Julia version 0.3.9 on Mac OS X 10.10.3

**Comment by ZacCranko** [comment] 2015-06-29 01:45
Working fine here on v0.3.10, can you try updating Julia then running `Pkg.update()` and see if this still persists?

**Comment by oyamad** [comment] 2015-06-29 02:00
Reproduced the same error message with version 0.3.10 + QuantEcon 0.1.2 (on Mac OS X 10.9.5),
while it works fine with 0.4.0-dev.

**Comment by ZacCranko** [comment] 2015-06-29 02:02
@oyamad can you run `Pkg.update()` on your v0.3 since we're calling some things from `Distributions.jl` that I want to exclude as potential causes.

**Comment by spencerlyon2** [comment] 2015-06-29 02:06
Thanks for reporting. I'm considering re-writing this routine anyway as I think we can make it more performant. Implementing an algorithm like what we just did in the numba version (the one with embedded bisection) may be faster than calling out to Categorical from Distributions.jl

**Comment by oyamad** [comment] 2015-06-29 02:09
@ZacCranko Got the same error.

**Comment by ZacCranko** [comment] 2015-06-29 02:15
I'm unable to reproduce this on v0.3.10 or v0.4.0-dev+5645

**Comment by spencerlyon2** [comment] 2015-06-29 02:27
Scratch my previous comment. I was confusing the new implementation of this algorithm with a different implementation I saw earlier.

I still wouldn't be surprised if using `searchsortedfirst` was more efficient than calling Categorical. Maybe we just write up an implementation and run some benchmarks against the two?

**Comment by ranjanan** [comment] 2015-06-29 13:07
@ZacCranko Just as @oyamad said, I'm getting the same error on Julia v0.3.10 on Mac OS X 10.10.3 as well. On a 16 day old master of Julia , I got this error while trying "using QuantEcon"

 using QuantEcon
Warning: New definition 
    serialize(Any, DataStructures.HashDict) at /Users/ranjan/.julia/v0.4/DataStructures/src/hashdict.jl:91
is ambiguous with: 
    serialize(Base.SerializationState, Any) at serialize.jl:399.
To fix, define 
    serialize(Base.SerializationState, DataStructures.HashDict)
before the new definition.
Warning: New definition 
    serialize(Any, DataStructures.HashDict) at /Users/ranjan/.julia/v0.4/DataStructures/src/hashdict.jl:91
is ambiguous with: 
    serialize(Base.IO, Any) at serialize.jl:421.
To fix, define 
    serialize(Base.IO, DataStructures.HashDict)
before the new definition.
Warning: New definition 
    deserialize(Any, Type{DataStructures.HashDict{#K<:Any, #V<:Any, #O<:Any}}) at /Users/ranjan/.julia/v0.4/DataStructures/src/hashdict.jl:100
is ambiguous with: 
    deserialize(Base.SerializationState, DataType) at serialize.jl:653.
To fix, define 
    deserialize(Base.SerializationState, Type{DataStructures.HashDict{#K<:Any, #V<:Any, #O<:Any}})
before the new definition.
ERROR: LoadError: LoadError: LoadError: UndefVarError: Range1 not defined
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /Users/ranjan/.julia/v0.4/Graphs/src/edge_list.jl, in expression starting on line 11
while loading /Users/ranjan/.julia/v0.4/Graphs/src/Graphs.jl, in expression starting on line 127
while loading /Users/ranjan/.julia/v0.4/QuantEcon/src/QuantEcon.jl, in expression starting on line 6

Building a new master now, and will report what happens next.

**Comment by spencerlyon2** [comment] 2015-06-29 13:12
@ranjanan, I've confirmed the issue on 0.3.9 and 0.3.10 also.

I'm implementing a fix right now.

The issue you just reported in the previous traceback indicates that the `Graphs.jl` package is not up to date for 0.4.

**Comment by ranjanan** [comment] 2015-06-29 13:15
Ah I see. Thanks, @spencerlyon2

**Comment by spencerlyon2** [comment] 2015-06-29 18:37
Closed by #53

**Closed by spencerlyon2** 2015-06-29 18:37 UTC
